set_property IOSTANDARD LVCMOS33 [get_ports RCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SER]
set_property IOSTANDARD LVCMOS33 [get_ports SRCLK]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN D19 [get_ports rst_n]
set_property PACKAGE_PIN U19 [get_ports SRCLK]
set_property PACKAGE_PIN Y19 [get_ports RCLK]
set_property PACKAGE_PIN W19 [get_ports SER]

set_property PACKAGE_PIN D19 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports DIO]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN Y18 [get_ports SCLK]
set_property PACKAGE_PIN Y16 [get_ports DIO]
