set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports data_out]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN T10 [get_ports data_out]
set_property PACKAGE_PIN D19 [get_ports rst]
