set_property IOSTANDARD LVCMOS33 [get_ports i_switch_1]
set_property IOSTANDARD LVCMOS33 [get_ports i_switch_2]
set_property IOSTANDARD LVCMOS33 [get_ports o_led_1]
set_property PACKAGE_PIN D19 [get_ports i_switch_1]
set_property PACKAGE_PIN D20 [get_ports i_switch_2]
set_property PACKAGE_PIN R14 [get_ports o_led_1]
