set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports lcd_e]
set_property PACKAGE_PIN W18 [get_ports lcd_rs]
set_property PACKAGE_PIN W19 [get_ports pwm_out]
set_property PACKAGE_PIN Y18 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN Y19 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN Y16 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN Y17 [get_ports {lcd_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_out]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_e]

set_property PACKAGE_PIN D20 [get_ports reset_n]
